
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https:;
      script-src 'self' https: 'unsafe-inline';
      style-src 'self' 'unsafe-inline' https:;
      img-src 'self' data: https:;
      connect-src 'self' https:;
    """

